KOD-Library init
mwiski/library pull request #1
Opened 2019-08-22 20:26 UTC by mwiski

2019-09-01 20:54 UTC, mps4dev requested changes
Bardzo ciężko się sprawdza kilka commitow na raz. Bo w każdym kolejnym komicie widzisz tylko zmiany w stosunku do poprzedniego komita. Prosiłbym o zmerdżowanie tych komitów razem i wypushowanie ich z flagą --force. Możesz użyć u siebie `git rebase -i HEAD~3` (poczytaj sobie, jak się to robi) a potem zrobić `git push --force` i dołączyć to do pull equesta

2019-09-01 20:54 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
> +    public BookCopyDto addBookCopy(@RequestParam Long titleId, @RequestParam String status) throws CannotPerformActionException {
przy request mappingach mamy taką konwencję, by były to rzeczowniki i pisane małymi literami. 
Tutaj na przyklad `book/copy`

2019-09-01 20:54 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
> +    public BorrowingDto borrowBook(@RequestParam Long bookCopyId, @RequestParam Long borrowerId, @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate borrowDate) throws CannotPerfor
Raczej nie dajemy @DateTimeFormat, a formatujemy sobie w serwisie

2019-09-01 20:54 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
> +        return libraryMapper.mapToBorrowerDtoList(service.getBorrowers());
logikę wykonujemy w serwisie (lącznie z mapowaniami)

2019-09-18 10:26 UTC, mps4dev requested changes
Nie uwzględniłeś mojej uwagi poprzedniej o tym, że logikę w serwisach nie w kontrolerach dajemy.

2019-09-18 10:26 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
> +        return libraryMapper.mapToTitleDto(service.saveTitle(libraryMapper.mapToTitle(titleDto)));
generalnie powinno być tak, że kontroler korzysta tylko z serwisów. Natomiast mappery powinny się znaleźć w serwisach :)

2019-09-18 19:55 UTC, mps4dev requested changes
:-1:

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
> +        return service.saveBorrower(borrowerDto);
metody serwisu nazywałbym (o ile się da) tak jak metody serwisu :) czyli np. `service.addBorrower` ;)

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      public BookCopyDto addBookCopy(@RequestParam Long titleId, @RequestParam String status) throws CannotPerformActionException {
metodę nazwałbym `addExemplar`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      public BookCopyDto changeBookCopyStatus(@RequestParam Long id, @RequestParam String status) throws CannotPerformActionException {
`updateExemplarStatus`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.PUT, value = "status/change")
`value = book/exemplar/status`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.POST, value = "borrower/add", consumes = APPLICATION_JSON_VALUE)
`value = "borrower"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.POST, value = "title/add", consumes = APPLICATION_JSON_VALUE)
`value = "book/title"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.POST, value = "book/copy/add", consumes = APPLICATION_JSON_VALUE)
`value = "book/exemplar"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.GET, value = "copies/available")
`value = "/book/exemplars"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.GET, value = "titles")
`value = "book/titles"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.GET, value = "books/copies")
`value = "book/exemplars"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/controller/LibraryController.java
>      @RequestMapping(method = RequestMethod.GET, value = "borrowings")
`value = "book/borrowings"`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BookCopy.java
>  public class BookCopy {
`Exemplar`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BookCopy.java
>  @Table(name = "books_copies")
`exemplars`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/Borrowing.java
>      @JoinColumn(name = "book_copy_id")
`exemplar_id`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/Borrowing.java
>      private BookCopy bookCopyId;
`Exemplar exemplarId`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/Title.java
> +    @Override
Czemu to dodałeś? Gdy używamy Hibernate, to trzeba być bardzo ostrożnym. Jeśli chcmy porównać dwa obiekty, z których przynajmniej jeden jest zarządzany przez Hibernate, to musimy porównywać ręcznie id-ki lub cale obiekty. 
Usuń eqals i hashCode

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/service/DbService.java
> +    public BorrowerDto saveBorrower(final BorrowerDto borrowerDto) {
`addBorrower`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/service/DbService.java
>      public int getAvailableBookCopiesNumber(final Long titleId) throws CannotPerformActionException {
getAvailableExemplars()

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/service/DbService.java
>          return bookCopyRepository.retrieveBookCopiesWithStatus("available", title).size();
enum

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/service/DbService.java
>          return bookCopyRepository.retrieveBookCopiesWithStatus("available", title).size();
użyj bezpośrednio metody ze spring data do liczenia ilości elementów zwróconych przez zapytanie.

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BookCopy.java
> +    private String status;
status zrob jako enum

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BookCopyDto.java
> +    private List<Borrowing> borrowings = new ArrayList<>();
`List<BorrowingDto>`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BorrowerDto.java
> +    private List<Borrowing> borrowings = new ArrayList<>();
`List<BorrowingDto>`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BorrowingDto.java
> +    private BookCopy bookCopyId;
`private long exemplarId` - jak masz `id` to raczej to będzie `long` a nie obiekt. Poniżej podobnie.

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/TitleDto.java
> +    private List<BookCopy> copies = new ArrayList<>();
`List<ExemplarDto>`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/mapper/LibraryMapper.java
> +    }
Jak widzisz, metody mapujące listy na listy są bardzo podobne. Nie chcemy powtarzać ciągle podobnego kodu. Można napisać sobie metodę:
`public static <E, D> List<D> getDtoList(Collection<E> entityList, Function<E, D> convertFunction) {
		if (entityList == null) return null;
		return entityList.stream()
				.map(convertFunction::apply)
				.collect(Collectors.toList());
	}` a następnie jej uzywać w metodach dedykowanych dla konkretnych mapowań
`

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/repository/BookCopyRepository.java
> +    List<BookCopy> retrieveBookCopiesWithStatus(@Param("available") String available, @Param("title") Title title);
użyj spring data `findAllByStatusAndTitle` oraz zrób metode defaultową 
`findAvailableByTitle(Title title) {return findAllByStatusAndTitle(AVAILABLE, title); }

2019-09-18 19:55 UTC, mps4dev commented on src/main/java/com/kodilla/library/domain/BookCopy.java
> +        query = "FROM BookCopy WHERE status LIKE :available AND title_id = :title"
u ciebie title jest obiektem, title_id jest mylne

2019-09-19 18:17 UTC, mwiski commented on src/main/java/com/kodilla/library/repository/BookCopyRepository.java
> +    List<BookCopy> retrieveBookCopiesWithStatus(@Param("available") String available, @Param("title") Title title);
Tak się zastanawiam, że chyba to niepotrzebne jest. Tzn. miałem tylko zliczać ile jest dostępnych egzemplarzy do wypożyczenia, czyli załóżmy metoda:
long countAllByStatusAndTitle(Status status, Title title);

2019-09-20 15:47 UTC, mwiski commented
Może zrobię rebase, żebyś lepiej widział całość?

2019-09-22 20:33 UTC, mps4dev approved these changes
:+1:

2019-09-23 11:54 UTC, merged